name: Generate JavaDoc

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22' 
          distribution: 'adopt'

      - name: Generate JavaDoc
        run: |
          cd jump-sturdy-ai
          mvn javadoc:javadoc

      - name: Deploy Javadoc to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: javadoc
          folder: jump-sturdy-ai/target/site/docs # folder to move
          token: ${{ secrets.GITHUB_TOKEN }}
