name: Generate JavaDoc

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22' 
          distribution: 'adopt'

      - name: Generate JavaDoc
        run: |
          cd jump-sturdy-ai
          mvn javadoc:javadoc

      - name: Deploy JavaDoc to javadoc branch
        run: |
          cd jump-sturdy-ai
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout --orphan javadoc
          git rm -rf .
          cp -r apidocs/* .
          git add .
          git commit -m "Deploy JavaDoc"
          git push origin javadoc --force
