name: Rename apidocs to docs and Deploy to GitHub Pages

on:
  push:
    branches:
      - javadoc

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rename apidocs to docs and clean up
        run: |
          if [ -d "apidocs" ]; then
            mv apidocs docs
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"
            git add docs
            git commit -m "Rename apidocs to docs and remove old folder"
            rm -rf apidocs
            git add -u  # Stage the removal of the old folder
            git commit -m "Remove old apidocs directory"
            git push
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: rename

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
