name: Rename apidocs to docs

on:
  push:
    branches:
      - javadoc

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rename apidocs to docs
        run: |
          if [ -d "apidocs" ]; then
            mv apidocs docs
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add docs
            git commit -m "renamed apidocs to docs"
            git push

            rm -rf apidocs
            git add -u  
            git commit -m "remove old apidocs directory"
            git push
          fi
